version: '3'
services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "c:\\work\\logscan-python:/root/logscan"
      - "c:\\work\\logscan_testdata:/root/testdata"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.1.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
